---
title: "Athlete Monitering Report"
output: html_document
params:
  athlete: NA
  tests: NA
  date.range: NA
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE)

library(knitr)
library(kableExtra)

```
### Athlete: **`r params$athlete`**  

### Date: `r Sys.Date()`  
#### Data Range: `r params$date.range[1]` to `r params$date.range[2]`  

#### This report was generated via the online WLTF Athlete Monitoring System. For further information please contact Sean at <sgaiesky@gmail.com>

```{r data_org}
url <- c("https://docs.google.com/spreadsheets/d/1fiRUwYv8FtysQQg7Z25Py-FW6KJeuMeoFCXuPmf89EE/edit?usp=sharing")
dat <- gsheet::gsheet2tbl(url)

dat$Date %<>% as.Date(format("%d/%m/%Y"))
dat$Athlete %<>% as.factor()
dat$Type %<>% as.factor()
dat$Season %<>% as.factor()

d <- dat %>%
        filter(Athlete %in% params$athlete &
               Type %in% params$tests & 
               #Season %in% input$season &
               Date >= params$date.range[1] &
               Date <= params$date.range[2])
```

```{r jump_report, fig.align='center'}

jump.graph <- ggplot(data = d, mapping = aes(x = Date, y = Score)) +
            geom_point(mapping = aes(colour = Type, shape = Athlete),
                       size = 3) +
            geom_line(mapping = aes(colour = Type, group = interaction(Athlete, Type),
                                    linetype = Athlete),
                      size = 1.2) +
            scale_x_date(date_breaks = "1 month",
                         date_labels = "%B %Y") +
            labs(y = "Height (mm)",
                 x = "") +
            guides(x = guide_axis(angle = 90)) +
            theme_classic() +
            theme(axis.text.x = element_text(face = "bold", size = 12),
                  legend.text = element_text(size = 12))

print(jump.graph)
```

```{r jump_tbl}

pb.tbl <- d %>%
            group_by(Athlete, Type, Season) %>%
            summarise(PB = max(Score),
                      Average = mean(Score)) %>%
            mutate_if(is.numeric, round, 0) %>%
            ungroup() %>%
            select(!Average) %>%
            pivot_wider(names_from = Type, values_from = PB)

avg.tbl <- d %>%
            group_by(Athlete, Type, Season) %>%
            summarise(PB = max(Score),
                      Average = mean(Score)) %>%
            mutate_if(is.numeric, round, 0) %>%
            ungroup() %>%
            select(!PB) %>%
            pivot_wider(names_from = Type, values_from = Average)


kbl(pb.tbl,
    align = c("l", rep("c",4))) %>%
  kable_styling(bootstrap_options = c("hover","striped"))

kbl(avg.tbl,
    align = c("l", rep("c",4))) %>%
  kable_styling(bootstrap_options = c("hover","striped"))
```

